name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '👋 Deprecated'
    labels:
      - 'deprecation'
  - title: '⛓  Dependency Updates'
    label:
      - 'library-update'
      - 'test-library-update'
      - 'dependencies'
  - title: '🛠  Internal Updates'
    label:
      - 'internal'
      - 'kaizen'
      - 'chore'
  - title: '📚 Docs'
    labels:
      - 'doc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'doc'
    files:
      - '*.md'
      - '*.yml'
      - '*.yaml'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'deprecation'
    title:
      - '/deprecate/i'
