---
name: Publish to RubyGems

on:
  push:
    # TODO: delete the branches key when we switch to using tags only
    branches:
      - push-gems
    tags:
      - v*

permissions:
  id-token: write
  contents: write

# see: https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
jobs:
  # push:
  #   name: Push gem to RubyGems.org
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Set up
  #     - uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: false
  #         ruby-version: 3.2
  #     - name: Install gem packages
  #       run: |
  #         gem install bundler
  #         bundle install --jobs 4 --retry 3

  #     # # Release
  #     # - uses: rubygems/release-gem@v1

  push-trino-client-ruby:
    # needs: push
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./trino-client-ruby
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.2
      - name: Install gem packages
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      # Release
      - run: rubygems/release-gem@v1
        working-directory: ./trino-client-ruby
