---
name: Publish to RubyGems

on:
  push:
    # # TODO: delete the branches key when we switch to using tags only
    # branches:
    #   - push-gems
    tags:
      - v*

permissions:
  id-token: write
  contents: write

# see: https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    steps:
      # Set up
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.2
      - name: Install gem packages
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # Release
      - uses: rubygems/release-gem@v1

  push-trino-client-ruby:
    # needs: push
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.2
      - name: Install gem packages
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      # Release
      # - uses: rubygems/release-gem@v1
      # see: https://github.com/rubygems/release-gem/blob/ebe1ec66bd8d2c709ac29aa2b43438d450e7a0a6/action.yml
      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0
      - name: Generate gem
        run: gem build trino-client-ruby.gemspec && ls -l trino-client-ruby-*.gem
        working-directory: ./trino-client-ruby
      - name: Push to rubygems.org
        run: gem push trino-client-ruby-*.gem
        working-directory: ./trino-client-ruby
